"""add_video_url_to_lesson_and_attachments_table

Revision ID: ede688d04d8a
Revises: a1b2c3d4e5f6
Create Date: 2026-06-12 16:35:36.766953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ede688d04d8a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lesson_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_lesson_id', 'attachments', ['lesson_id'], unique=False)
    op.drop_index(op.f('ix_badges_course_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_slug'), table_name='badges')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_verification_code'), table_name='certificates')
    op.drop_constraint(op.f('uq_certificate_user_course'), 'certificates', type_='unique')
    op.alter_column('lab_submissions', 'language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_submissions_user_lab'), table_name='lab_submissions')
    op.alter_column('labs', 'language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.add_column('lessons', sa.Column('video_url', sa.String(length=2048), nullable=True))
    op.add_column('lessons', sa.Column('video_provider', sa.String(length=50), nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('BADGE_AWARDED', 'COURSE_COMPLETED', 'CERTIFICATE_ISSUED', 'QUIZ_PASSED', 'LAB_PASSED', 'PROJECT_GRADED', 'COURSE_ASSIGNED', 'INCIDENT', 'ACHIEVEMENT', 'COURSE', 'REMINDER', name='notificationtype'),
               type_=sa.Enum('BADGE_AWARDED', 'COURSE_COMPLETED', 'CERTIFICATE_ISSUED', 'QUIZ_PASSED', 'LAB_PASSED', 'PROJECT_GRADED', 'COURSE_ASSIGNED', 'ACHIEVEMENT', 'COURSE', 'REMINDER', 'INCIDENT', name='notificationtype', native_enum=False),
               existing_nullable=False,
               postgresql_using="type::text::notificationtype")
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.execute("ALTER TABLE project_submissions ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE project_submissions ALTER COLUMN status TYPE VARCHAR(20) USING status::varchar")
    op.execute("UPDATE project_submissions SET status = 'PENDING' WHERE status NOT IN ('PENDING','REVIEWING','APPROVED','REJECTED')")
    op.execute("ALTER TABLE project_submissions ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.drop_index(op.f('ix_projects_course_id'), table_name='projects')
    op.alter_column('questions', 'correct_answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_index(op.f('ix_scorm_packages_course_id'), table_name='scorm_packages')
    op.drop_index(op.f('ix_training_profiles_slug'), table_name='training_profiles')
    op.drop_constraint(op.f('training_profiles_name_key'), 'training_profiles', type_='unique')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.alter_column('user_progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progressstatus', native_enum=False),
               existing_nullable=False,
               postgresql_using="status::text")
    op.create_index('ix_user_progress_user_module_lesson', 'user_progress', ['user_id', 'module_id', 'lesson_id'], unique=False)
    op.drop_constraint(op.f('user_progress_enrollment_id_fkey'), 'user_progress', type_='foreignkey')
    op.drop_constraint(op.f('user_progress_lesson_id_fkey'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_progress', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_training_profile_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_training_profile_id'), 'users', ['training_profile_id'], unique=False)
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_progress_lesson_id_fkey'), 'user_progress', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('user_progress_enrollment_id_fkey'), 'user_progress', 'enrollments', ['enrollment_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_user_progress_user_module_lesson', table_name='user_progress')
    op.alter_column('user_progress', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progressstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_unique_constraint(op.f('training_profiles_name_key'), 'training_profiles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_training_profiles_slug'), 'training_profiles', ['slug'], unique=False)
    op.create_index(op.f('ix_scorm_packages_course_id'), 'scorm_packages', ['course_id'], unique=False)
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.alter_column('questions', 'correct_answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_projects_course_id'), 'projects', ['course_id'], unique=False)
    op.alter_column('project_submissions', 'status',
               existing_type=sa.Enum('PENDING', 'REVIEWING', 'APPROVED', 'REJECTED', name='projectstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('BADGE_AWARDED', 'COURSE_COMPLETED', 'CERTIFICATE_ISSUED', 'QUIZ_PASSED', 'LAB_PASSED', 'PROJECT_GRADED', 'COURSE_ASSIGNED', 'ACHIEVEMENT', 'COURSE', 'REMINDER', 'INCIDENT', name='notificationtype', native_enum=False),
               type_=postgresql.ENUM('BADGE_AWARDED', 'COURSE_COMPLETED', 'CERTIFICATE_ISSUED', 'QUIZ_PASSED', 'LAB_PASSED', 'PROJECT_GRADED', 'COURSE_ASSIGNED', 'INCIDENT', 'ACHIEVEMENT', 'COURSE', 'REMINDER', name='notificationtype'),
               existing_nullable=False)
    op.drop_column('lessons', 'video_provider')
    op.drop_column('lessons', 'video_url')
    op.alter_column('labs', 'language',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_lab_submissions_user_lab'), 'lab_submissions', ['user_id', 'lab_id'], unique=False)
    op.alter_column('lab_submissions', 'language',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_certificate_user_course'), 'certificates', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_certificates_verification_code'), 'certificates', ['verification_code'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_badges_slug'), 'badges', ['slug'], unique=False)
    op.create_index(op.f('ix_badges_course_id'), 'badges', ['course_id'], unique=False)
    op.drop_index('ix_attachments_lesson_id', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
