"""add_areas_table

Revision ID: f62fd384365f
Revises: d874eb74a2b6
Create Date: 2026-07-30 22:04:38.710993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62fd384365f'
down_revision: Union[str, None] = 'd874eb74a2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('area_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_area_id'), 'users', ['area_id'], unique=False)
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_area_id'), table_name='users')
    op.drop_column('users', 'area_id')
    op.drop_table('areas')
    # ### end Alembic commands ###
